# Generated by Django 2.0.7 on 2020-01-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='features',
            new_name='featured',
        ),
    ]
